### ISSUE TITLE
Services getting 400 Bad Request

### ISSUE THREAD

**Issue by antchong** [M365-DenzilFernandes/PowerBI-MessageCenter#1]
after update tenant id , client ID and Client secret, services data source got 400 Bad request error.

**Comment by antchong** [comment]
when i click go to error, get Json windows will pop up

**Comment by M365-DenzilFernandes** [comment]
can you pls try to update the connection on the queries, set to anonymous and the url from the drop down is matching the query uri. click connect.

**Comment by antchong** [comment]
issue fix beside O365Token need to update tenant ID services also need to replace one more time thanks
