### ISSUE TITLE
Have had an issue pulling data

### ISSUE THREAD

**Issue by AndrewMarsh24** [M365-DenzilFernandes/PowerBI-MessageCenter#2]
Tested this today with a correctly set up app registration i am using and i get

Web.Contents failed to get contents from 'https://manage.office.com/api/v1.0/b69556a7-a6a2-43ef-a377-205c1627fc77/ServiceComms/Services' (400): Bad Request

this is on the query for "services" others fail with Loading blocked by failures with other queries.

**Comment by M365-DenzilFernandes** [comment]
Can you refresh the O365Token query? Then after try the other queries. Each query needs the authentication to be set to anonymous. See the other issue as it's similar to yours.

**Comment by AndrewMarsh24** [comment]
Thanks, so cleared the permissions in data source settings.

checked my tenant id, secret and client ID and all good.

Checked my applied steps in "o365token" and looks good. 

I opened advanced editor on all 5 queries and then added my tenant id to the remaining 4

close and apply to all, reauth against anonymous 
first prompt goes ok 
2nd prompt goes ok
3rd fails (looks like message centre query)

so now down to a new error: 
The credentials provided for the Web source are invalid. Please update the credentials through a refresh or in the Data Source Settings dialog to continue. (Source at https://manage.office.com/api/v1.0/mytenantID/ServiceComms/Services.)

my API permissions in app registration: 

![image](https://user-images.githubusercontent.com/56106861/103445396-5cf98480-4c6b-11eb-981d-1786a7cacbf3.png)

**Comment by AndrewMarsh24** [comment]
looking a bit deeper (and my BI knowledge is poor)

the services query fails, in applied steps, the tenant_id and the get_uri are fine its the "getJSON" it seems to stumble at.

**Comment by AndrewMarsh24** [comment]
OK so each query has a "source" as a first step. the services one doesnt in applied steps, would that be the factor?

**Comment by M365-DenzilFernandes** [comment]
correct each query has a source that you need to successfully connect to using anonymous authentication. Before you update that run the query to get the O365Token

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AndrewMarsh24** [comment]
edited in advanced editor to include the source from the token, no different

The credentials provided for the Web source are invalid. Please update the credentials through a refresh or in the Data Source Settings dialog to continue. (Source at https://manage.office.com/api/v1.0/mytenantID/ServiceComms/Services.)

**Comment by AndrewMarsh24** [comment]
novice, can you let me know how i run the query to get the O365Token

**Comment by AndrewMarsh24** [comment]
Sorted, started again and worked fine. thanks for the help. close this out

**Comment by M365-DenzilFernandes** [comment]
Awesome! Glad you got it going.
