### ISSUE TITLE
not authenticating once uploading to a workspace 

### ISSUE THREAD

**Issue by AndrewMarsh24** [M365-DenzilFernandes/PowerBI-MessageCenter#3]
Random question, love the work and working for us on BI desktop. AP registration is pulling data, When i then publish it to a workspace the data connections fail on the bottom 3 web queries and then dont authorise so i cant then schedule a refresh. Dont suppose you have any idea? about to kill it all and rebuild it from scratch.

**Comment by AndrewMarsh24** [comment]
Same if i delete and re-add, its as if the first web query approves but the 2/3/4 dont.

**Comment by M365-DenzilFernandes** [comment]
Sorry I haven't updated this to run into a workspace for automatic refresh. This would require an Azure Function that can do the data refresh. The reason for this is that Power BI doesn't support an anonymous authentication refresh schedule.

**Comment by M365-DenzilFernandes** [comment]
I've updated and provided a new solution that would use Power Automate with a premium connection to download the data via Service Comm's API. Then render the PBI dashboard from those files. Now you can enable automatic refresh on the dataset.
