### ISSUE TITLE
Update New 

### ISSUE THREAD

**Issue by Prash-Ever** [M365-DenzilFernandes/PowerBI-MessageCenter#4]
Hi @M365-DenzilFernandes  - Looks like legacy the Service Communications API no longer supported and it is replaced with Microsoft Graph. 

Can you please make this solution working again with new MS Graph API ?

**Comment by M365-DenzilFernandes** [comment]
Hi, Yes you are right. It expired back in Jan and I noticed it wasn't working anymore. I've updated a solution that uses Power Automate (Graph Calls) and saves files to a SharePoint Site. Then from there, I am using PowerBI to update the report. The reason I am doing this now since the report cannot be refreshed if published to PBI Service.

**Comment by M365-DenzilFernandes** [comment]
Btw which method were you using Option 1 (PBI Direct Query to Service) or Option 2 (Via Power Automate)

**Comment by Prash-Ever** [comment]
> Btw which method were you using Option 1 (PBI Direct Query to Service) or Option 2 (Via Power Automate)

Thanks for your prompt response, @M365-DenzilFernandes . 
I tried both option 1 as well as option 2 but no luck. I guess, they still have reference to legacy API... Can you please confirm, updated version of Power Automate is uploaded to your solution ?   

![image](https://user-images.githubusercontent.com/30252741/166162061-d5931b0f-ec00-4fe7-ad2f-ccb4e90da8db.png)

**Comment by M365-DenzilFernandes** [comment]
I haven't yet uploaded my changes. I have Option 2 Updated with new calls to graph. I am looking at the effort to update Option 1 now

**Comment by M365-DenzilFernandes** [comment]
I've uploaded Option 2 using Power Automate - Here are the two files. Import the PA into your environment and set up the locations to save the files. Then in Query editor for PBI update the location references to your site.

https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/raw/main/Microsoft365AdminCenter-MessageCenter-Public-v3.0.pbix

https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/raw/main/PBI-ServiceCommunicationstoTextFile%5BExport%5D-v3.0.zip

**Comment by M365-DenzilFernandes** [comment]
Just testing out option 1 after changing it to use graph.microsoft.com. It's looking good so far. Thanks again @Prash-Ever ; with your comment, I would have not been challenged to update it. 

![image](https://user-images.githubusercontent.com/64493972/166163819-83bc416b-631f-4529-a908-3afc689d9579.png)

I will upload my changes when complete

**Comment by M365-DenzilFernandes** [comment]
I've updated Option 1 as well now. This is a direct query to graph. Unfortunately, it's throttled to 100 records. I'll look into how I can loop through all the records later. 

You can test this out, add your Tenant/App/Secret to the O365Token Query.
https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/raw/main/Microsoft365AdminCenter-MessageCenter-Public-v3.0-Direct.pbix

**Comment by Prash-Ever** [comment]
> I've uploaded Option 2 using Power Automate - Here are the two files. Import the PA into your environment and set up the locations to save the files. Then in Query editor for PBI update the location references to your site.
> 
> https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/raw/main/Microsoft365AdminCenter-MessageCenter-Public-v3.0.pbix
> 
> https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/raw/main/PBI-ServiceCommunicationstoTextFile%5BExport%5D-v3.0.zip

Thanks @M365-DenzilFernandes but power automate is throwing a forbidden 403 error while executing Get-Message block. Please confirm, do i need to grant **additional permission** and / or **Roles** to AAD App ?  

![image](https://user-images.githubusercontent.com/30252741/166214940-e806300b-b963-4adb-9c0d-c5e62f99fed7.png)

AAD App

![image](https://user-images.githubusercontent.com/30252741/166217368-28991e26-f2f6-4d5a-8f12-40c579afe730.png)

**Comment by M365-DenzilFernandes** [comment]
Check for these two API's and let me know: Permission Type is "Application" 

ServiceMessage.Read.All
ServiceHealth.Read.All

![image](https://user-images.githubusercontent.com/64493972/166252980-240952f3-3938-40d1-9ee7-67510901eab1.png)

**Comment by Prash-Ever** [comment]
> Check for these two API's and let me know: Permission Type is "Application"
> 
> ServiceMessage.Read.All ServiceHealth.Read.All
> 
> ![image](https://user-images.githubusercontent.com/64493972/166252980-240952f3-3938-40d1-9ee7-67510901eab1.png)

Thank You - It works and able to generate CSV.
