### ISSUE TITLE
Not able to get O365 token - We couldn't authenticate with the credentials providede

### ISSUE THREAD

**Issue by LakurCz** [M365-DenzilFernandes/PowerBI-MessageCenter#5]
Hello Denzil, I'm from Microsoft PACE team and one of our client's raised a question that he is not able to setup the dashboard. 
I tried to repro the issue or make it work but unfortunately it doesn't work for me either. We are just not able to get the token.

When I Create an app in azure.portal.com/ grant all the necessary permissions (Service.Health + Service.Message) which is needed.
![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/139482002/ada8888a-6563-4925-9866-5674571c1377)

Then I'm rewriting the tenant ID + Client ID + Secret key in your pbix file as described 
![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/139482002/47a638dd-ee66-46fc-b34e-9988e2a67d1a)

I just can't authenticate myself
![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/139482002/f18bd645-450b-401c-b909-32e22499b8e3)

We are trying the Option1 and downloading the pbix from the App registration part - https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter#azure-ad-app-registration
This one https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/raw/main/Microsoft365AdminCenter-MessageCenter-Public.pbix

I'm posting this issue on behalf of the client. 

If can help us solve this problem, it will be awesome!

Thanks, Daniel

**Comment by M365-DenzilFernandes** [comment]
Thanks for explaining the issue. Can you please try this pbix file instead...
https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/blob/main/Microsoft365AdminCenter-MessageCenter-Public-v3.0.pbix

**Comment by LakurCz** [comment]
Thanks for your answer but unfortunately with this link (pbix) -https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/raw/main/Microsoft365AdminCenter-MessageCenter-Public-v3.0-Direct.pbix
Its the same thing 
![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/139482002/b6ca1131-6306-4674-953a-2a1f185264d8)
![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/139482002/58685ffd-b800-4453-a04f-3e8f2c2b4080)

TenantID/ClientID:
![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/139482002/2e8f49f8-cb1d-40f9-821e-6c37d485c14b)
Secret:
![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/139482002/4be3d468-bb28-4335-862c-d61b06defa81)

**Comment by LakurCz** [comment]
Oh I see now, you provided link with the sharepoint - https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/raw/main/Microsoft365AdminCenter-MessageCenter-Public-v3.0.pbix

As Client is not able to use Automate Flows in his company, we can't implement Options 2 :(

**Comment by M365-DenzilFernandes** [comment]
There are two solutions. I am providing assistance to Option 1. This uses a direct query from PBI to the tenant's message center and doesn't require Power Automate. 

In this report, when you edit the transform, all connections use "Anonymous". There is no authentication here. Instead, the authentication is happening inside the query which contains the values you have updated or replaced. 

Can you start over using the link for the report I provided? 
https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/raw/main/Microsoft365AdminCenter-MessageCenter-Public-v3.0.pbix

![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/64493972/2140cbae-d2dc-4e9f-842b-0f88cf2c9604)

![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/64493972/d5caf326-d043-4842-8b0c-ca6afb23adf3)

**Comment by LakurCz** [comment]
Hello Denzil, the link which you provided https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/raw/main/Microsoft365AdminCenter-MessageCenter-Public-v3.0.pbix redirect me to file which is using sharepoint and there is no any graph.microsoft.com inside of the DataSource Settings. 

This is what I can see in that file you shared 
![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/139482002/509c2b20-7fb6-4143-95a5-aa76bbd3bdb6)

If you sent a wrong one and it should be the this one https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/raw/main/Microsoft365AdminCenter-MessageCenter-Public-v3.0-Direct.pbix with the "ending" direct. I tested that and I'm still getting authentication error. Once I change the values of tenantID, objectID, secretID PBI wants from me to authenticate and I'm not able to do that. Before that I changed every connection to Anonymous and it didn't help
![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/139482002/ad7d58e1-524d-49d7-af06-99c4d3b1a872)

Thanks for helping.

**Comment by M365-DenzilFernandes** [comment]
Correct on the PBIX file, we need to use the direct query. Sorry idky when I paste links its not giving you the right file. 

Notice on this data source when I edit it.. Using anonymous on the login,microsoftonline.com link I don't see a drop down. I saw that in your client you had a URL there *your 1st post screenshot.

![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/64493972/faf00deb-9c45-465d-b14f-1c947f38ece5)

My PBI Desktop version is , try to see if you have something equivalent or newer as well.
![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/64493972/37d318ca-ebfb-445c-8bee-49f12bca686d)

**Comment by LakurCz** [comment]
I'm trying to do the same steps but always I get to the Access Web Content Windows and get the error .
![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/139482002/13d62cf9-7e04-4987-bcc2-7aa4043c584b)

I have here a short video - How I'm, trying to setup the dashboard - https://microsofteur-my.sharepoint.com/:v:/g/personal/v-dhaborak_microsoft_com/EUZkMYhzG51Inuen_vDi-OoBpXFgUD5-PWnQuMIObPjOWA?e=N1hMsd (hope you can access it)

If I discard changes, the O365 token get updated with these tenantID/clientID/client_secret. I don't know where they are from. 
![image](https://github.com/M365-DenzilFernandes/PowerBI-MessageCenter/assets/139482002/b7137ee7-4411-4b19-8964-dbd946f2e5a1)

**Comment by M365-DenzilFernandes** [comment]
Thanks for the video. I saw that you clicked "Clear Permission" just before setting up the report. Can you bypass that step? The report I have uploaded/saved has that already configured.

**Comment by LakurCz** [comment]
No worries. I skipped the step but its the same thing :( . Have a look https://microsofteur-my.sharepoint.com/:v:/g/personal/v-dhaborak_microsoft_com/ERRX1oZi_whLlsE5jEKzWfQB7C9yM2zL0Jk2yYbg08_kDA?e=eg8khv. Or drop me your email if you are willing to have a call about that. 

Have a look what happened after Discard Changes, thats very strange. 
Thanks

**Comment by LakurCz** [comment]
Hello Denzil, will you be able to help on this? We can stay in touch on teams, thanks.

**Comment by M365-DenzilFernandes** [comment]
The issue was related to the secret. Used Secret ID vs Value
